version: '3'
services:
    web:
        build: .
        links:
          - db
        ports:
          - "9000:9000"
        volumes:
          - ".:/app"
    db:
      image: mysql:5.7
      ports:
        - "32000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: test